name: Build and Deploy
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build site
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Shanghai"

    - name: Check Time
      run: date

    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Check yarn / node version
      run: |
        echo "yarn version `yarn --version`"
        echo "node version `node -v`"

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-

    - name: Install Dependencies
      run: yarn install

    - name: Build Site
      run: yarn docs:build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: 'sustech-online-build'
        path: './docs/.vuepress/dist/'

  deploy:
    name: Deploy site
    runs-on: "ubuntu-latest"
    needs: build
    if: always() && github.repository_owner == 'SUSTC' && github.ref == 'refs/heads/master'
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: sustech-online-build
        path: "./docs/.vuepress/dist/"

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: "./docs/.vuepress/dist/"

    - name: Deploy to GitHub page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./docs/.vuepress/dist/
        force_orphan: true

    # - name: Deploy to coding
    #   uses: liziwl/git-push-action@v1.0.4
    #   with:
    #     git_token_holder: 'pt5ez622q7ct'
    #     git_token: '${{ secrets.CODING_TOKEN }}'
    #     commit_user: 'liziwl'
    #     commit_email: 'leezisy@gmail.com'
    #     push_dir: './docs/.vuepress/dist/'
    #     repository_url: 'e.coding.net/liziwl/sustech-online/sustech-online-pages.git'
    #     keep_history: false
    #     branch: master

    - name: copy file to server PVG
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: "./docs/.vuepress/dist/"
        target: ${{ secrets.HTML_PATH }}
        rm: true
        strip_components: 4

    - name: copy file to server SZX
      uses: burnett01/rsync-deployments@5.0
      with:
        switches: -avzr --delete
        path: "./docs/.vuepress/dist/"
        remote_path: ${{ secrets.HTML_PATH_SZX }}
        remote_host: ${{ secrets.HOST_SZX }}
        remote_user: ${{ secrets.USERNAME_SZX }}
        remote_key: ${{ secrets.SSH_KEY_SZX }}

    - name: setup aliyun oss
      uses: manyuanrong/setup-ossutil@master
      with:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        access-key-id: ${{ secrets.OSS_KEY_ID }}
        access-key-secret: ${{ secrets.OSS_KEY_SECRET }}
    - name: cp files to aliyun
      run: |
        ossutil rm -rf oss://perf-sustech-online/*
        ossutil cp -rf docs/.vuepress/dist/ oss://perf-sustech-online/
